# sources.mk - what native.mk and guest.mk both build: the same files with the
# same defines, so the native reference and the sandboxed core are the same
# program. Included, not run.

ROOT := ..
POP2 := $(ROOT)/extern/SDLPoP2/source
MB   ?= $(or $(MINIBOX_DIR),$(HOME)/chimera/extern/chimera-common-minibox)

# ---- SDLPoP2, upstream: the library its own meson build makes (source/
# meson.build sdlpop2Sources), less coro.c - the core's coro.c takes its place
# (ucontext is not in musl, and a stack must be asked for as one; see coro.c).
# Nothing of it uses SDL: the SDL frontend is sdl/, which the core is instead.
POP2_NAMES := anim audio audio_opl3 beast blades caverns char cheats collision control \
	core dat fight final frame game glue guard heads hooks image input items kid kidctl kind1 kind5 \
	level lever5 loader menu mobs nis render render_desc render_frame render_hooks render_kind2 \
	render_kind3 render_kind4 render_kind_common render_kind_desc render_ovl37f0 render_palette \
	render_screen render_sprites render_tiles room roomhooks ruins seq shadow13 shell skeleton sound \
	spirit state temple text tick tiles trap walls bridge5 settings replay
POP2_SRCS := $(addprefix $(POP2)/,$(addsuffix .c,$(POP2_NAMES)))
# as SDLPoP2's meson.build: gnu11, a release build, -Wall
POP2_CFLAGS_COMMON := -std=gnu11 -O2 -I$(POP2)

# ---- Munt's libmt32emu, the Roland MT-32 (the submodule extern/munt, at the
# commit OpenSamurai's core builds): the library its CMake build makes
# (mt32emu/CMakeLists.txt libmt32emu_CPP_SOURCES), less the resamplers that
# need libsoxr or libsamplerate and the version tagging of a shared object.
# C++; Munt's own flags are its CMake defaults.
MUNT := $(ROOT)/extern/munt/mt32emu/src
MUNT_NAMES := Analog BReverbModel Display File FileStream LA32FloatWaveGenerator LA32Ramp LA32WaveGenerator \
	MidiStreamParser Part Partial PartialManager Poly ROMInfo Synth Tables TVA TVF TVP sha1/sha1 SampleRateConverter \
	c_interface/c_interface srchelper/srctools/src/FIRResampler srchelper/srctools/src/SincResampler \
	srchelper/srctools/src/IIR2xResampler srchelper/srctools/src/LinearResampler srchelper/srctools/src/ResamplerModel \
	srchelper/InternalResampler
MUNT_SRCS := $(addprefix $(MUNT)/,$(addsuffix .cpp,$(MUNT_NAMES)))
# its config.h, generated by CMake upstream: the core's own (munt-config.h)
MUNT_CONFIG := $(ROOT)/build/munt-config/config.h
$(MUNT_CONFIG): munt-config.h
	@mkdir -p $(dir $@)
	cp munt-config.h $@
MUNT_CXXFLAGS_COMMON := -std=c++11 -O2 -I$(ROOT)/build/munt-config -I$(MUNT)

# ---- the core
CORE_NAMES := pop2-driver game-state coro files sha1 wbx-entry
# SDLPoP2's own headers too: the core's objects compile against them (the
# game's globals, the shell's interface), and a new SDLPoP2 changes them without
# touching a file here - game-state.o survived one such bump and read garbage
CORE_HDRS := pop2-driver.h sha1.h settings.inc $(MUNT_CONFIG) $(wildcard $(POP2)/*.h)

# the calls the core answers itself (files.c)
WRAP_FLAGS := -Wl,--wrap=fopen

# the patch series goes onto the submodule before anything of SDLPoP2 builds
PATCH_STAMP := $(ROOT)/build/patches.stamp
$(PATCH_STAMP): $(wildcard $(ROOT)/patches/*.patch) apply-patches.sh
	sh apply-patches.sh
	@mkdir -p $(dir $@)
	@touch $@

# Every object depends on the flags it was built with: a change to them
# rebuilds it. (A flag change that rebuilds nothing has bitten these cores: a
# red-zone object two weeks older than the flag that forbade it.)
define flags_stamp
$(shell mkdir -p $(1); printf '%s\n' '$(2)' | cmp -s - $(1)/flags || printf '%s\n' '$(2)' > $(1)/flags)
endef
